zenben_git_homepage:
    pattern:  /
    defaults: { _controller: ZENbenGitBundle:Default:index }

zenben_git_status:
    pattern:  /status/{id}
    defaults: { _controller: ZENbenGitBundle:Default:status }
