parameters:

services:
  zengit.github:
    class: ZENben\GitBundle\Service\GitHub\GitHubService
    arguments: ['%github_token%', '@router']

  zengit.twig.utils:
    class: ZENben\GitBundle\Twig\UtilsExtension
    tags:
      - { name: twig.extension }