default:
    resource: "@DefaultBundle/Resources/config/routing.yml"
    prefix:   /

foosball:
    resource: "@FoosballBundle/Resources/config/routing.yml"
    prefix:   /foosball

zengit:
    resource: "@ZENbenGitBundle/Resources/config/routing.yml"
    prefix:   /zen-git