ZENben\FoosballBundle\Entity\Game\Tournament:
    type: entity
    table: game_tournament
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
        description:
            type: string
    oneToMany:
        signups:
            targetEntity: ZENben\FoosballBundle\Entity\Game\TournamentSignup
            mappedBy: tournament
            orderBy: { date: desc }
        matches:
            targetEntity: ZENben\FoosballBundle\Entity\Game\Match
            mappedBy: tournament
    oneToOne:
        game:
            targetEntity: ZENben\FoosballBundle\Entity\Game\Game
    lifecycleCallbacks: {  }
