ZENben\FoosballBundle\Entity\Game\Game:
    type: entity
    table: game
    repositoryClass: ZENben\FoosballBundle\Repository\Game\GameRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        active:
            type: boolean
        type:
            type: string
        game_id:
            type: integer
        yammer_group:
            type: integer
            nullable: true
        dateStart:
            type: datetime
            column: date_start
        dateEnded:
            type: datetime
            column: date_ended
            nullable: true
    oneToMany:
        updates:
            targetEntity: ZENben\FoosballBundle\Entity\Game\GameUpdate
            mappedBy: game
            orderBy: { dateCreated: desc, id: desc }
        matches:
            targetEntity: ZENben\FoosballBundle\Entity\Game\Match
            mappedBy: game
            orderBy: { match_id: asc }
    lifecycleCallbacks: {  }
