parameters:
    foosball.oauth.user_provider.class: ZENben\FoosballBundle\Security\UserProvider\OAuthUserProvider
    foosball.oauth.user_provider.entity: ZENben\FoosballBundle\Entity\User\User

services:
    foosball.oauth.user_provider.service:
        class: %foosball.oauth.user_provider.class%
        arguments:
            - '@doctrine'
            - %foosball.oauth.user_provider.entity%
            - google: google_id
    foosball.twig.foosball:
        class: ZENben\FoosballBundle\Twig\FoosballExtension
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@game'
          - '@foosball.oauth.user_provider.service'
        tags:
          - { name: twig.extension }

    game:
        class : ZENben\FoosballBundle\Service\GameService
        arguments:
          - '@doctrine.orm.entity_manager'
          - %foosball.game%
          - '@event_dispatcher'
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
                
    #foosball.listener.yammer:
    #    class: ZENben\FoosballBundle\Listener\YammerListener
    #    arguments: ['@yammer', '@translator', '@logger']
    #    tags:
    #        - { name: kernel.event_listener, event: foosball.game.updated, method: onGameUpdate }